CutLink/CutLink/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls"))
]

CutLink/shop/urls.py
from django.urls import path
from . import views as shop_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', shop_views.home, name="home"),
    path('about/', shop_views.about, name="about"),
    path('reg/', shop_views.reg, name="reg"),
    path('auth/', auth_views.LoginView.as_view(template_name="shop/auth.html"), name="auth"),
    path('exit/', auth_views.LogoutView.as_view(template_name="shop/exit.html"), name="exit"),
    path('profile/', shop_views.profile, name="profile"),
    path('urls/', shop_views.urls, name="urls"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CutLink/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True, null=True)
    image = models.ImageField(upload_to="profile_pictures", default="photo_default.png")
    text = models.TextField(default="Я так обожаю сладкий раф с сахаром и карамельным сиропом :)")
    
    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"
        
    def __str__(self):
        return f"Профиль пользователя {self.user}"
    
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 256 or img.width > 256:
            resize = (256, 256)
            img.thumbnail(resize)
            img.save(self.image.path)
            
            
class Url(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_url = models.TextField()
    second_url = models.TextField()
    
    
    class Meta:
        verbose_name = "Ссылка"
        verbose_name_plural = "Ссылки"
        
    def __str__(self):
        return f"Ссылка пользователя {self.user}"

CutLink/shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Url


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    username = forms.CharField(label="",
                               max_length=1024,
                               required=True,
                               widget=forms.widgets.TextInput(attrs={
                                   "display": "block",
                                   "class": "username-block css-input",
                                   "placeholder": "Введите ваш Логин",
                                   "helptext": "",
                               }))

    password1 = forms.CharField(label="",
                                max_length=1024,
                                required=True,
                                widget=forms.widgets.PasswordInput(attrs={
                                    "display": "block",
                                    "class": "password1-block css-input",
                                    "placeholder": "Придумайте надежный пароль",
                                }))

    password2 = forms.CharField(label="",
                                max_length=1024,
                                required=True,
                                widget=forms.widgets.PasswordInput(attrs={
                                    "display": "block",
                                    "class": "password2-block css-input",
                                    "placeholder": "Подтвердите пароль",
                                }))


class UpdateLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    username = forms.CharField(label="",
                               max_length=1024,
                               widget=forms.widgets.TextInput(attrs={
                                   "display": "block",
                                   "class": "username-block css-input",
                                   "helptext": "",
                               }))

    email = forms.CharField(label="",
                            max_length=1024,
                            required=False,
                            widget=forms.widgets.TextInput(attrs={
                                "display": "block",
                                "class": "email-block css-input",
                                "helptext": "",
                            }))


class UpdateTextForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['text']

    text = forms.CharField(label="",
                           max_length=1024,
                           widget=forms.widgets.TextInput(attrs={
                               "display": "block",
                               "class": "big-text-block css-input",
                               "helptext": "",
                           }))


class UpdateImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

    image = forms.ImageField(label="Загрузить фото", widget=forms.FileInput)


class AddUrl(forms.ModelForm):
    class Meta:
        model = Url
        fields = ['first_url', 'second_url']

    first_url = forms.CharField(widget=forms.widgets.TextInput(attrs={
                                "display": "block",
                                "class": "css-input url-link",
                                "placeholder": "Введите вашу ссылку",
                                }))

    second_url = forms.CharField(widget=forms.widgets.TextInput(attrs={
        "display": "block",
        "class": "css-input url-link",
        "placeholder": "Введите имя для ссылки",
    }))

CutLink/shop/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, AddUrl
from django.contrib import messages
from .forms import UpdateLoginForm, UpdateTextForm, UpdateImageForm
from django.contrib.auth.decorators import login_required
from .models import Url

# Create your views here.
def home(request):
    return render(request, 'shop/home.html', {
        "title": "CUTLINK"
    })
    
    
def about(request):
    return render(request, 'shop/about.html', {
        "title": "CUTLINK"
    })
    
    
def reg(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            messages.success(request, f"Добро пожаловать, {username}")
            form.save()
            return redirect('home')
        return render(request, 'shop/reg.html', {
            "title": "Регистрация",
            "form": form
        })
    else:
        form = RegistrationForm()
        return render(request, 'shop/reg.html', {
            "title": "Регистрация",
            "form": form
        })
        

@login_required
def profile(request):
    if request.method == "POST":
        loginform = UpdateLoginForm(request.POST, instance=request.user)
        textform = UpdateTextForm(request.POST, instance=request.user.profile)
        imageform = UpdateImageForm(request.POST, request.FILES, instance=request.user.profile)
        print(textform.is_valid())
        print(imageform.is_valid())
        print(loginform.is_valid())
        if textform.is_valid() and loginform.is_valid() or imageform.is_valid():
            if textform.is_valid() and loginform.is_valid():
                loginform.save()
                textform.save()
                messages.success(request, f"Профиль обновлен!")
                return redirect("profile")
            else:
                imageform.save()
            messages.success(request, f"Профиль обновлен!")
            return redirect("profile")
    loginform = UpdateLoginForm(instance=request.user)
    textform = UpdateTextForm(instance=request.user.profile)
    imageform = UpdateImageForm(instance=request.user.profile)
    data = {
        "title": "Личный кабинет",
        "loginform": loginform,
        "textform": textform,
        "imageform": imageform,
    }
    return render(request, "shop/profile.html", data)


def urls(request):
    if request.method == "POST":
        form = AddUrl(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.second_url = "link/" + instance.second_url
            instance.save()
            return redirect("urls")
    
    form = AddUrl()
    data = {
        "title": "Мои ссылки",
        "form": form,
        "request": request,
    }
    return render(request, "shop/urls.html", data)

CutLink/shop/templates/shop/about.html
{% extends "shop/base.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}

<h1>Легко сократим вашу ссылку</h1>
    <div class="about-ul">
        {% if not user.is_authenticated %}
        <div><span class="span-url"><a href="{% url "reg" %}">Зарегистрируйтесь</a></span> на сайте</div>
        {% else %}
        <div>Перейдите в раздел <span class="span-url"><a href="{% url "home" %}">Ссылки</a></span></div>
        {% endif %}
        <div>Введите ссылку на необходимый вам ресурс</div>
        <div>Нажмите кнопку <span class="span-btn">Сократить!</span></div>
    </div>

{% endblock main %}

CutLink/shop/templates/shop/auth.html
{% extends "shop/base.html" %}

{% block title %}
    {{ authorization }}
{% endblock title %}

{% block main %}

<h1>Войти в аккаунт</h1>
<div class="div-form">
    <form method="POST" class="reg-form">
        {% csrf_token %}
            {{ form }}
            <div class="btn-div">
                <button type="submit" class="btn btn-black">Готово</button>
            </div>
    </form>
</div>
{% endblock main %}

CutLink/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "shop/style.css" %}">
    <link rel="stylesheet" href="{% static "shop/fontawesome-free-6.6.0-web/css/all.min.css" %}">
</head>
<body>
    <header class="header">
        <div class="logo">
            <img src="{% static "shop/logo.png" %}" alt="logo" width="100">
        </div>
        <div class="logo-text">
            CUT<i class="fa-solid fa-scissors skissors"></i>LINK
        </div>
        <div class="btns">
            <a class="btn" href="{% url "home" %}">Главная</a>
            <a class="btn" href="{% url "about" %}">Про нас</a>
            {% if user.is_authenticated %}
            <a class="btn" href="{% url "profile" %}">Профиль</a>
            <a class="btn" href="{% url "urls" %}">Ссылки</a>
            {% else %}
            <a class="btn" href="{% url "reg" %}">Зарегистрироваться</a>
            <a class="btn" href="{% url "auth" %}">Войти</a>
            {% endif %}
        </div>
    </header>
    <main class="main">
        {% block main %}
        {% endblock main %}
    </main>
    <footer class="footer">
        <div class="footer-text">
            <span>&copy; 2024</span>
            <span>Грачев Николай Романович</span>
            <span>Все права защищены.</span>
        </div>
        {% if messages %}
        <div class="message-div">
            {% for mess in messages %}
                {{ mess }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="icons">
            <a href="https://t.me/Nick331045"><i class="fa-brands fa-telegram icon"></i></a>
            <a href="mailto:gracevnikolaj220@gmail.com"><i class="fa-regular fa-envelope icon"></i></a>
            <a href="https://vk.com/yakapustaa"><i class="fa-brands fa-vk icon"></i></a>
        </div>
    </footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static "shop/index.js" %}"></script>
</body>
</html>

CutLink/shop/templates/shop/exit.html
{% extends "shop/base.html" %}

{% block title %}
    {{ Exit }}
{% endblock title %}

{% block main %}
<h1>Вы успешно вышли из аккаунта</h1>
<div class="exit-btn-div eb">
    <a href={% url "auth" %}>Войти</a>
</div>
{% endblock main %}

CutLink/shop/templates/shop/home.html
{% extends "shop/base.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}

<div class="big_p typewriter">
    <p>C U T L I N K</p>
</div>
<div class="mini_p">Быстро сократим любую ссылку для вашего проекта</div>
    {% if not user.is_authenticated %}
    <a href="{% url "reg" %}">
        <div class="big-btn">Зарегистрироваться</div></a>
    {% else %}
    <a href="{% url "profile" %}">
        <div class="big-btn">Личный кабинет</div></a>
    {% endif %}
{% endblock main %}

CutLink/shop/templates/shop/profile.html
{% extends "shop/base.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}
<div class="profile-block">
    <div class="up">
        <div class="left">
            <img src="{{ user.profile.image.url }}" alt=":(" width="256" height="256">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ imageform }}
                <button type="submit" class="btn image">Сохранить</button>
            </form>
        </div>
        <div class="right">
            <form method="POST" class="profile-form">
                {% csrf_token %}
                <div>Контактная информация</div>
                <div>Никнейм: {{ loginform.username }}</div>
                <div>Email: {{ loginform.email }}</div>
                <div>Немного обо мне</div>
                <div class="big-text">{{ textform }}</div>
                <button type="submit" class="btn bnt-text">Сохранить</button>
            </form>
        </div>
</div>
<div>
    <form action="{% url "exit" %}" method="POST" class="profile-btn btn exit-btn-div eb">
        {% csrf_token %}
        <button>Выйти</button>
    </form>
</div>
    
    

{% endblock main %}

CutLink/shop/templates/shop/reg.html
{% extends "shop/base.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}

<h1>Регистрация</h1>
<div class="div-form">
    <form method="POST" class="reg-form">
        {% csrf_token %}
            {{ form }}
            <div class="btn-div">
                <button type="submit" class="btn btn-black">Готово</button>
            </div>
    </form>
</div>
{% endblock main %}

CutLink/shop/templates/shop/urls.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Мои ссылки</title>
    <link rel="stylesheet" href="{% static "shop/style.css" %}">
    <link rel="stylesheet" href="{% static "shop/fontawesome-free-6.6.0-web/css/all.min.css" %}">
</head>
<body>
    <header class="header fixed">
        <div class="logo">
            <img src="{% static "shop/logo.png" %}" alt="logo" width="100">
        </div>
        <div class="logo-text">
            CUT<i class="fa-solid fa-scissors skissors"></i>LINK
        </div>
        <div class="btns">
            <a class="btn" href="{% url "home" %}">Главная</a>
            <a class="btn" href="{% url "about" %}">Про нас</a>
            <a class="btn" href="{% url "profile" %}">Профиль</a>
            <a class="btn" href="{% url "urls" %}">Ссылки</a>
        </div>
    </header>
    <main class="url-main">
        <div class="url-form reg-form">
            <form method="POST" class="url-full-form">
                {% csrf_token %}
                {{ form }}
                <button class="btn url-btn">Сократить</button>
            </form>
        </div>
        <div class="all-urls">
        {% for url in request.user.url_set.all %}
            <div class="url">
                <a href="{{url.first_url}}">{{url.second_url}}</a>
            </div>
        {% empty %}
        <div class="not-url">Еще нет сокращенных ссылок</div>
        {% endfor %}
        </div>
    </main>
    <footer class="footer fixed">
        <div class="footer-text">
            <span>&copy; 2024</span>
            <span>Грачев Николай Романович</span>
            <span>Все права защищены.</span>
        </div>
        <div class="icons">
            <a href="https://t.me/Nick331045"><i class="fa-brands fa-telegram icon"></i></a>
            <a href="mailto:gracevnikolaj220@gmail.com"><i class="fa-regular fa-envelope icon"></i></a>
            <a href="https://vk.com/yakapustaa"><i class="fa-brands fa-vk icon"></i></a>
        </div>
    </footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static "shop/index.js" %}"></script>
</body>
</html>